spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=db_web;encrypt=false;
    username: SA
    password: Password1477!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      platform: mssql

oauth:
  kakao:
    client-id: 8tJLZMOJa9yCZ9yV5Y57
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: Ucz6F7zlAB
    client-id: 8tJLZMOJa9yCZ9yV5Y57
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

jwt:
  secret-key: Z29uZ2NoZWNrLWdvbmdjaGVjay1nb25nY2hlY2stZ29uZ2NoZWNrCg123456789Z29uZ2NonY2hlY2stZ29uZ2NoZWNrCg123456789
  access_token_expire_milsec: 3600000 # 1시간
  refresh_token_expire_milsec: 3600000 # 1시간
  token_type: Bearer #접속 토큰 타입