spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=database_web;encrypt=false;
    username: SA
    password: password1477!

  jpa:
    show-sql: true

  sql:
    init:
      platform: mssql